[
    { "name": "Flour", "group": "Grain" },
    { "name": "Salt", "group": "Seasoning" },
    { "name": "Sugar", "group": "Sweetener" },
    { "name": "Olive oil", "group": "Oil" },
    { "name": "Butter", "group": "Dairy" },
    { "name": "Eggs", "group": "Protein" },
    { "name": "Milk", "group": "Dairy" },
    { "name": "Vanilla extract", "group": "Flavoring" },
    { "name": "Baking powder", "group": "Leavening agent" },
    { "name": "Baking soda", "group": "Leavening agent" },
    { "name": "Yeast", "group": "Leavening agent" },
    { "name": "Cocoa powder", "group": "Chocolate" },
    { "name": "Chocolate chips", "group": "Chocolate" },
    { "name": "Honey", "group": "Sweetener" },
    { "name": "Almonds", "group": "Nut" },
    { "name": "Walnuts", "group": "Nut" },
    { "name": "Pecans", "group": "Nut" },
    { "name": "Peanuts", "group": "Nut" },
    { "name": "Coconut flakes", "group": "Fruit" },
    { "name": "Blueberries", "group": "Fruit" },
    { "name": "Strawberries", "group": "Fruit" },
    { "name": "Bananas", "group": "Fruit" },
    { "name": "Oranges", "group": "Fruit" },
    { "name": "Lemons", "group": "Fruit" },
    { "name": "Limes", "group": "Fruit" },
    { "name": "Ginger", "group": "Root vegetable" },
    { "name": "Garlic", "group": "Root vegetable" },
    { "name": "Onions", "group": "Vegetable" },
    { "name": "Bell peppers", "group": "Vegetable" },
    { "name": "Tomatoes", "group": "Fruit" },
    { "name": "Cilantro", "group": "Herb" },
    { "name": "Parsley", "group": "Herb" },
    { "name": "Basil", "group": "Herb" },
    { "name": "Mint", "group": "Herb" },
    { "name": "Rosemary", "group": "Herb" },
    { "name": "Oregano", "group": "Herb" },
    { "name": "Thyme", "group": "Herb" },
    { "name": "Pepper", "group": "Seasoning" },
    { "name": "Chili powder", "group": "Spice" },
    { "name": "Cumin", "group": "Spice" },
    { "name": "Nutmeg", "group": "Spice" },
    { "name": "Cinnamon", "group": "Spice" },
    { "name": "Paprika", "group": "Spice" },
    { "name": "Saffron", "group": "Spice" },
    { "name": "Turmeric", "group": "Spice" },
    { "name": "Cloves", "group": "Spice" },
    { "name": "Allspice", "group": "Spice" },
    { "name": "Coriander", "group": "Spice" },
    { "name": "Soy sauce", "group": "Sauce" },
    { "name": "Worcestershire sauce", "group": "Sauce" },
    { "name": "Hot sauce", "group": "Sauce" },
    { "name": "Vinegar", "group": "Acid" },
    { "name": "Rice", "group": "Grain" },
    { "name": "Quinoa", "group": "Grain" },
    { "name": "Pasta", "group": "Grain product" },
    { "name": "Bread", "group": "Grain product" },
    { "name": "Oats", "group": "Grain" },
    { "name": "Corn", "group": "Grain" },
    { "name": "Chickpeas", "group": "Legume" },
    { "name": "Lentils", "group": "Legume" },
    { "name": "Black beans", "group": "Legume" },
    { "name": "Kidney beans", "group": "Legume" },
    { "name": "Green beans", "group": "Vegetable" },
    { "name": "Zucchini", "group": "Vegetable" },
    { "name": "Broccoli", "group": "Vegetable" },
    { "name": "Cauliflower", "group": "Vegetable" },
    { "name": "Carrots", "group": "Root vegetable" },
    { "name": "Beets", "group": "Root vegetable" },
    { "name": "Potatoes", "group": "Root vegetable" },
    { "name": "Sweet potatoes", "group": "Root vegetable" },
    { "name": "Spinach", "group": "Leafy green" },
    { "name": "Kale", "group": "Leafy green" },
    { "name": "Lettuce", "group": "Leafy green" },
    { "name": "Arugula", "group": "Leafy green" },
    { "name": "Cabbage", "group": "Vegetable" },
    { "name": "Brussels sprouts", "group": "Vegetable" },
    { "name": "Asparagus", "group": "Vegetable" },
    { "name": "Peas", "group": "Legume" },
    { "name": "Mushrooms", "group": "Fungus" },
    { "name": "Pineapple", "group": "Fruit" },
    { "name": "Mango", "group": "Fruit" },
    { "name": "Apple", "group": "Fruit" },
    { "name": "Pear", "group": "Fruit" },
    { "name": "Grapes", "group": "Fruit" },
    { "name": "Kiwi", "group": "Fruit" },
    { "name": "Peach", "group": "Fruit" },
    { "name": "Nectarine", "group": "Fruit" },
    { "name": "Plum", "group": "Fruit" },
    { "name": "Cherries", "group": "Fruit" },
    { "name": "Watermelon", "group": "Fruit" },
    { "name": "Cantaloupe", "group": "Fruit" },
    { "name": "Honeydew", "group": "Fruit" },
    { "name": "Raspberries", "group": "Fruit" },
    { "name": "Blackberries", "group": "Fruit" },
    { "name": "Cranberries", "group": "Fruit" },
    { "name": "Pomegranate", "group": "Fruit" },
    { "name": "Avocado", "group": "Fruit" },
    { "name": "Coconut", "group": "Fruit" },
    { "name": "Tofu", "group": "Protein" },
    { "name": "Chicken", "group": "Protein" },
    { "name": "Beef", "group": "Protein" },
    { "name": "Pork", "group": "Protein" },
    { "name": "Lamb", "group": "Protein" },
    { "name": "Turkey", "group": "Protein" },
    { "name": "Fish", "group": "Protein" },
    { "name": "Shrimp", "group": "Protein" },
    { "name": "Crab", "group": "Protein" },
    { "name": "Lobster", "group": "Protein" },
    { "name": "Mussels", "group": "Protein" },
    { "name": "Clams", "group": "Protein" },
    { "name": "Oysters", "group": "Protein" },
    { "name": "Salmon", "group": "Protein" },
    { "name": "Tuna", "group": "Protein" },
    { "name": "Trout", "group": "Protein" },
    { "name": "Mackerel", "group": "Protein" },
    { "name": "Cod", "group": "Protein" },
    { "name": "Haddock", "group": "Protein" },
    { "name": "Sardines", "group": "Protein" },
    { "name": "Anchovies", "group": "Protein" },
    { "name": "Sesame seeds", "group": "Seed" },
    { "name": "Chia seeds", "group": "Seed" },
    { "name": "Sunflower seeds", "group": "Seed" },
    { "name": "Flax seeds", "group": "Seed" },
    { "name": "Pumpkin seeds", "group": "Seed" },
    { "name": "Poppy seeds", "group": "Seed" },
    { "name": "Mustard seeds", "group": "Seed" },
    { "name": "Fennel seeds", "group": "Seed" },
    { "name": "Sesame oil", "group": "Oil" },
    { "name": "Canola oil", "group": "Oil" },
    { "name": "Coconut oil", "group": "Oil" },
    { "name": "Vegetable oil", "group": "Oil" },
    { "name": "Grapeseed oil", "group": "Oil" },
    { "name": "Peanut oil", "group": "Oil" },
    { "name": "Almond oil", "group": "Oil" },
    { "name": "Sour cream", "group": "Dairy" },
    { "name": "Yogurt", "group": "Dairy" },
    { "name": "Cream", "group": "Dairy" },
    { "name": "Parmesan", "group": "Cheese" },
    { "name": "Mozzarella", "group": "Cheese" },
    { "name": "Cheddar", "group": "Cheese" },
    { "name": "Swiss", "group": "Cheese" },
    { "name": "Gouda", "group": "Cheese" },
    { "name": "Feta", "group": "Cheese" },
    { "name": "Brie", "group": "Cheese" },
    { "name": "Camembert", "group": "Cheese" },
    { "name": "Blue cheese", "group": "Cheese" },
    { "name": "Goat cheese", "group": "Cheese" },
    { "name": "Cream cheese", "group": "Cheese" },
    { "name": "Ricotta", "group": "Cheese" },
    { "name": "Cottage cheese", "group": "Dairy" },
    { "name": "Maple syrup", "group": "Sweetener" },
    { "name": "Agave nectar", "group": "Sweetener" },
    { "name": "Molasses", "group": "Sweetener" },
    { "name": "Brown sugar", "group": "Sweetener" },
    { "name": "Powdered sugar", "group": "Sweetener" },
    { "name": "Raw sugar", "group": "Sweetener" }
]